channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - pip
  - pip:
    - git+https://github.com/MAAP-Project/stac_ipyleaflet.git#egg-info=stac_ipyleaflet@v0.3.3
variables:
  TITILER_STAC_ENDPOINT: https://staging-stac.delta-backend.com
  TITILER_ENDPOINT: https://staging-raster.delta-backend.com
  STAC_CATALOG_NAME: VEDA STAC
  STAC_CATALOG_URL: https://staging-stac.delta-backend.com/
  STAC_BROWSER_URL: http://veda-staging-stac-browser.s3-website-us-west-2.amazonaws.com/


