name: tile-benchmarking
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - carbonplan_data
    - geojson-pydantic==0.6.2
    - jupytext==1.14.7
    - loguru==0.7.0
    - ndpyramid
    - papermill==2.4.0
    - psycopg==3.1.9
    - psycopg-binary==3.1.9
    - psycopg-pool
    - pypgstac==0.7.9
    - rio_stac<0.7,>=0.6
    - rio-tiler==4.1.11
    - titiler-pgstac
    - titiler
