name: docker-base-images

on: workflow_dispatch

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: sergeysova/jq-action@v2

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_USER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_USER_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: docker build, tag, and push custom images
        run: |
          # get a list of all base Dockerfiles
          DOCKERFILES=$(find ./docker-images/base/* -name "Dockerfile")

          #####################
          # loop through and build ony if image doesn't exist on remote with our tags
          while read DOCKERFILE_PATH; do
            VERSION=$(cat $DOCKERFILE_PATH | grep VERSION | cut -d'=' -f 2)
            NAME_AND_DESC=$(echo $DOCKERFILE_PATH | cut -d'/' -f 4)
            PARENT_DIR=$(echo $DOCKERFILE_PATH | xargs -I{} dirname {})

            # check if repo does not exist
            existing_repo_uri=$(aws ecr-public describe-repositories | jq '.repositories | map(.repositoryUri)' | grep "$NAME_AND_DESC" | sed 's/,//g' | xargs)
            echo "###################################"
            echo "FOUND EXISTING REPO: $existing_repo_uri"
            echo "###################################"
            if [[ -z "$existing_repo_uri" ]]; then
              aws ecr-public create-repository \
                --repository-name "$NAME_AND_DESC" \
                --catalog-data=description='veda-base-image',architectures='x86-64',operatingSystems='Linux' \
                --tags=Key='org',Value='NASA' \
                --tags=Key='project',Value='VEDA'

              # now get the URI again so we can use it when we build
              existing_repo_uri=$(aws ecr-public describe-repositories | jq '.repositories | map(.repositoryUri)' | grep "$NAME_AND_DESC" | sed 's/,//g' | xargs)
            fi

            image_exists=$(aws ecr-public describe-images --repository-name "$NAME_AND_DESC" --image-ids=imageTag="$VERSION" | jq '.imageDetails | map(.repositoryName)' | grep "$NAME_AND_DESC" | xargs)
            echo "###################################"
            echo "FOUND EXISTING IMAGE WITH TAG: $image_exists=$VERSION"
            echo "###################################"
            if [ -z "$image_exists" ]; then
              echo "###################################"
              echo "BUILDING BASE IMAGE..."
              echo "###################################"
              pushd $PARENT_DIR

              DOCKERFILE_DIGEST=$(sha256sum ./Dockerfile | cut -d' ' -f1)
              DATE_TAG=$(date +%F)

              # login
              aws ecr-public get-login-password | docker login --username AWS --password-stdin public.ecr.aws

              # build image
              docker build \
                -t $existing_repo_uri:$VERSION \
                -t $existing_repo_uri:$DATE_TAG\
                -t $existing_repo_uri:$DOCKERFILE_DIGEST \
                -t $existing_repo_uri:latest .

              # push image to ECR
              docker push --all-tags $existing_repo_uri
              popd
            fi
          done < <(echo "$DOCKERFILES")
